name: metricbeat-staging

instance_groups:
- name: metricbeat
  instances: 1
  azs:       [z1]
  stemcell:  default
  vm_type: default
  networks:
    - name: default
  jobs:
   name: metricbeat
   release: metricbeat
   properties:
    modules:
      enabled: []
    kibana:
      host: ((kibana_host))
    elasticsearch:
      hosts: ((elasticsearch_hosts))
update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
- alias:   default
  os:      ubuntu-xenial
  version: latest

releases:
- name:    metricbeat
  version: latest